### ISSUE TITLE
zusätzliche manuelle GeräteListe

### ISSUE THREAD

**Issue by StMB2023** [psi-4ward/AskSinAnalyzerXS#100]
Hi ich habe 3 CCUs bei mir am laufen und dadurch sehe ich sehr viele IDs.
Leider kann ich nur eine Liste abrufen.
Gibt es eine Möglichkeit eine manuelle Device Liste zu pflegen oder mehrere CCUs ab fragen? bzw. könnte bitte jemand so eine Funktion einbauen ?

LG
Stefan

**Comment by psi-4ward** [comment]
Du kannst dir deine eigene DeviceList anlegen und statt einer URL einen Dateipfad angeben: https://github.com/psi-4ward/AskSinAnalyzerXS/blob/master/app/src/deviceList.ts#L99
