### ISSUE TITLE
erneutes Laden der DeviceList

### ISSUE THREAD

**Issue by demel42** [psi-4ward/AskSinAnalyzerXS#13]
Das Mapping der HM-Geräte-Adressen wird zur Zeit einmalig beim Start des Dienstes von der CCU respektive anderer Datenquellen geholt.

Wenn man nun Änderungen an der CCU vornimmt, sei es neue Geräte anlernt oder Geräte umbenennt, werden diese nicht berücksichtigt, bevor man neu startet.

Es wäre daher praktisch, wenn eine Funktion in der Web-GUI zur Verfügung stehen würde um einen Reload der DeviceListe auslösen zu können.

**Comment by psi-4ward** [comment]
* Der Button `SPEICHERN UND INITIALISIEREN` holt die die DeviceList
* In b1e0209bc011b92b98e7ba2037f425596f5c10f7 wurde ein refrecht jede Stunde implementiert
