### ISSUE TITLE
HTTP->HTTPS Weiterleitung führt zu "Error fetching device list: 301 Moved Permanently" Fehler

### ISSUE THREAD

**Issue by Yannik** [psi-4ward/AskSinAnalyzerXS#15]
Hi,

meine OCCU erlaubt aus Sicherheitsgründen nur HTTPS-Zugriffe, und leitet HTTP-Zugriffe automatisch nach HTTPS um.

Leider führt das zum o.g. Fehler `Error fetching device list: 301 Moved Permanently`. 

Wäre es möglich, den Schema-Teil der URL ebenfalls im Input-Feld einzugeben (oder ein HTTP/HTTPS Toggle)? Das würde IMO der richtige Weg, da es MITM-Angriffe verhindert.

**Comment by Yannik** [comment]
Ich habe testweise den Toggle "Device-List Backend ist eine CCU" ausgeschaltet und dann `https://occu.xxx.org/ret.exe?ret=dom.GetObject(ID_SYSTEM_VARIABLES).Get(%22AskSinAnalyzerDevList%22).Value()` als URL angegeben.

Das führt nun zu folgendem Fehler:
```
Error fetching device list: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
```

Ouch :-(

**Comment by psi-4ward** [comment]
Also wenn du dir Gedanken über MITM im local-net machst ... aber ja, Paranoia is applied security :)
Probier bitte mal die aktuelle Dev-Version.
