### ISSUE TITLE
Version in Docker "latest" always: 0.0.0

### ISSUE THREAD

**Issue by roe1974** [psi-4ward/AskSinAnalyzerXS#22]
Hi
I always see "Version:0.0.0"
<img width="1209" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/91692181-3c100e00-eb69-11ea-9447-e3d137a06286.PNG">
 in Docker latest Version ... is this normal ?
thx, Richard

**Comment by psi-4ward** [comment]
This is cause you use the latest development build. See https://github.com/psi-4ward/AskSinAnalyzerXS/releases

You can pull a tagged image for a specific version. (ie psitransfer:1.6.1)
