### ISSUE TITLE
Small blemish in the graphical view...

### ISSUE THREAD

**Issue by roe1974** [psi-4ward/AskSinAnalyzerXS#23]
Hi

There is a small blemish in the graphical view ... The bullet of the first actuator in the list (here e.g. "Alarmanlage") is cut off slightly at the top :-) ... You only see it when the list has a second page or more.

<img width="672" alt="Unbenannt" src="https://user-images.githubusercontent.com/30420568/91712733-a2f0ef80-eb88-11ea-8883-df895d2a7b56.PNG">

br, Richard

**Comment by psi-4ward** [comment]
Sorry that is too insignificant for further investigation 😉

**Comment by roe1974** [comment]
OK ;-)

**Comment by psi-4ward** [comment]
Wenn du magst kannst ja nen pull request vorbereiten 😁
