### ISSUE TITLE
Handle HTTP upgrade header

### ISSUE THREAD

**Issue by anoymouserver** [psi-4ward/AskSinAnalyzerXS#28]
Using this behind a (nginx) reverse proxy with HTTPS causes the browser to block the websocket connection, since it's scheme is `ws://` instead of the secure `wss://`.
As a result most of the UI is not working.

Maybe handling the upgrade with [server.handleUpgrade()](https://github.com/websockets/ws/blob/master/doc/ws.md#serverhandleupgraderequest-socket-head-callback) could help.

**Comment by psi-4ward** [comment]
2df5b91

**Comment by psi-4ward** [comment]
does it work for you?

**Comment by anoymouserver** [comment]
Yes, works well .. thank you!
_(sorry, I've missed the message initially)_
