### ISSUE TITLE
Installation on Raspberry not working

### ISSUE THREAD

**Issue by KingKahn123** [psi-4ward/AskSinAnalyzerXS#33]
Hi,

when trying to create the docker container on RaspBerry PI 4 I get following error message:

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error

Is this docker image not working with Raspberry PI OS?

Thx for your help,
Kai

**Comment by psi-4ward** [comment]
Yes atm only for x86 but you can try to build it on the raspberry yourself

**Comment by KingKahn123** [comment]
I am only a beginner using docker... So this would exceed my capabilities ;-)

**Comment by psi-4ward** [comment]
Not really. Download or clone this repository.
Run `docker build . -t psitransfer` in the folder where the Dockerfile is located. This builds you the image `psitransfer`

**Comment by KingKahn123** [comment]
This ends with following error message:

Step 4/13 : COPY /app /tmp/src/app
COPY failed: file not found in build context or excluded by .dockerignore: stat app: file does not exist

**Comment by psi-4ward** [comment]
Hmm should work. I'll give it a try myself tomorrow.

**Comment by KingKahn123** [comment]
ok thanks!

**Comment by KingKahn123** [comment]
Do you had a chance to try it yourself?

**Comment by psi-4ward** [comment]
Ha, you're right. The Dockerfile is in `Docker/Dockerfile` so you need adjust that:

```bash
docker build . -t analyzer -f Docker/Dockerfile
```

**Comment by KingKahn123** [comment]
Thx, now it works!
