### ISSUE TITLE
Alert hooks

### ISSUE THREAD

**Issue by psi-4ward** [psi-4ward/AskSinAnalyzerXS#4]
Wenn gewisse thresholds überschritten werden soll ein http call ausgeführt werden können um zB eine service Meldung zu erzeugen oder einen redmatic flow anzustoßen.

**Comment by HMSteve** [comment]
Warst wieder mal schneller als ich mit dem feature request😀
Aus etwas Erfahrung mit den Alerts des ESP-basierten Analyzer: Die zwei Nutzerparameter 
1. Obergrenze des normalen Rauschpegels
2. Obergrenze fuer die Dauer der ununterbrochen Ueberschreitung derer
sind schon sehr gut. False positives liefert mir am ehesten ein Update des EPaper Display (OTA noch nicht getestet). Deshalb der Gedanke fuer einen dritten Parameter, der den Zeitzaehler gem. 2. fuer eine gewisse Zeit abhaengig von der Anzahl der empfangenen namensaufloesbaren Pakete anhaelt. Dann koennte 2. kleiner gewaehlt werden. 
Das waere m.E. schon eine ganz gute grundlegende BI- und Jamming-Erkennung.

**Comment by psi-4ward** [comment]
Ich schließe dieses Ticket mal.
RSSI-Noise Alert-Trigger ist seit dca87ed2cac2f992d3227de5ae7620279355f6b3 implementiert.

Wenn jemand Bedarf an Device-spezifischen DC Alerts hat möge es Kundtun. 

Alternativ lassen sich auch Auswertungen über beispielsweise NodeRED durchführen, siehe https://github.com/psi-4ward/AskSinAnalyzerXS/blob/master/docs/NodeRED.md
