### ISSUE TITLE
No devices showing in Analyzer

### ISSUE THREAD

**Issue by PottiMc** [psi-4ward/AskSinAnalyzerXS#62]
I managed to connect my NanoCul-Stick to the Analyzer and it's showing me the RSSI Noise in my environment. What is not working is showing me the devices. Using version 1.7.1 of the Analyzer.

The CCU script created the device list and requesting it in the browser is actually returning a JSON list.

Do I miss something or is this an issue?

![image](https://user-images.githubusercontent.com/39881308/147349072-adf005db-c5c1-4a82-b07d-5f881a9d2b59.png)

![image](https://user-images.githubusercontent.com/39881308/147349117-ec42970e-b801-4d91-899a-7336556ebf2b.png)

Console Log;
![image](https://user-images.githubusercontent.com/39881308/147348668-e9adaa59-23e0-4661-ae3d-4882e4720dfe.png)

**Comment by psi-4ward** [comment]
Your sniffer does not receive any telegrams. Probably better you ask the Q in https://homematic-forum.de/forum/viewtopic.php?f=76&t=56395 - I dont have any exp with these CULs

**Comment by PottiMc** [comment]
I found the solution. Didn't change the GPIO-Mapping according to your instruction and as mentioned here: https://homematic-forum.de/forum/viewtopic.php?f=76&t=56395&start=10#p562580
Now it works fine.
