### ISSUE TITLE
Allow other serial device names

### ISSUE THREAD

**Issue by KoMa1978** [psi-4ward/AskSinAnalyzerXS#95]
In Linux running as a service, only default device names are selectable like /dev/ttyUSB3.

As this may change during a boot or if using another USB port, it would be great if you can choose a serial connection like "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0".

This is a symbolic link to the valid /dev/ttyUSBX device.

**Comment by psi-4ward** [comment]
```shell
$ docker run --rm --name analyzer --device=/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 psitrax/asksinanalyzer \
asksin-analyzer-xs  -d /data -p /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

Data-Path: /data
Server started on port 8081
Serving UI from /usr/local/lib/node_modules/asksin-analyzer-xs/htdocs
Connected to /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
I: AskSin++ V4.1.6 (Jul 17 2020 13:16:09)
I: CC init1
I: CC Version: 04
I: - ready
I: Config Freq: 0x2165DA
```

Works as expected. Only little drawback would be that [`serialport`](https://github.com/serialport/node-serialport/) does not enumerate serial-devices by id but anyhow - think your intend is to specify it manually.

**Comment by KoMa1978** [comment]
Changing it in the userdata.json also works fine.
I wasn't aware that this is a limitation of [serialport](https://github.com/serialport/node-serialport/)

Thanks a lot,

**Comment by psi-4ward** [comment]
Yes it's just the same 👍🏻
